import { PearlElement } from "../pearls/PearlElement";
import { LevelDefinition } from "./LevelDefinition";

export const levels = [
	{
		x: 560,
		y: 238,
		title: "Snail",
		key: "snail",
		require: [],
		enemy: "snail",
		background: "background_plains_0",
		music: "m_fight",
		pearl: PearlElement.None,
	},
	{
		x: 1142,
		y: 217,
		title: "Noctua",
		key: "noctua",
		require: ["jester"],
		enemy: "bat",
		background: "background_plains_0",
		music: "m_fight",
		pearl: PearlElement.None,
	},
	{
		x: 448,
		y: 520,
		title: "Smake",
		key: "smake",
		require: ["snail"],
		enemy: "snake",
		background: "background_ice",
		music: "m_lightfast",
		pearl: PearlElement.Coil,
	},
	{
		x: 742,
		y: 704,
		title: "Moler",
		key: "moler",
		require: ["smake", "jester"],
		enemy: "mole",
		background: "background_plains_2",
		music: "m_fight",
		pearl: PearlElement.Rock,
	},
	{
		x: 875,
		y: 391,
		title: "Jester",
		key: "jester",
		require: ["snail"],
		enemy: "jester",
		background: "background_plains_4",
		music: "m_lightfast",
		pearl: PearlElement.Psychic,
	},
	{
		x: 1485,
		y: 306,
		title: "Arba",
		key: "arba",
		require: ["noctua", "lycante"],
		enemy: "abra",
		background: "background_magma",
		music: "m_lightfast",
		pearl: PearlElement.Fire,
	},
	{
		x: 1216,
		y: 597,
		title: "Lycante",
		key: "wolf",
		require: ["jester", "moler"],
		enemy: "lycante",
		background: "background_ice",
		music: "m_fight",
		pearl: PearlElement.Water,
	},
	{
		x: 1576,
		y: 627,
		title: "Frassle",
		key: "badger",
		require: ["arba", "lycante"],
		enemy: "badger",
		background: "background_ice",
		music: "m_fight",
		pearl: PearlElement.Ice,
	},
] as const satisfies LevelDefinition[];

export type LevelKeys = (typeof levels)[number]["key"];
export type LevelKeysList<T> = { [K in LevelKeys]: T };
