import { LevelDefinition } from "./LevelDefinition";

export const levels: LevelDefinition[] = [
	{
		x: 400,
		y: 540,
		title: "Sans",
		key: "1",
		require: [],
		enemy: "sans",
		background: "background_plains_0",
	},
	{
		x: 800,
		y: 340,
		title: "Snake",
		key: "2a",
		require: ["1"],
		enemy: "snake",
		background: "background_plains_1",
	},
	{
		x: 800,
		y: 740,
		title: "Empty",
		key: "2b",
		require: ["1"],
		enemy: "",
		background: "background_plains_2",
	},
	{
		x: 1200,
		y: 340,
		title: "Empty",
		key: "3a",
		require: ["2a"],
		enemy: "",
		background: "background_plains_3",
	},
	{
		x: 1200,
		y: 740,
		title: "Empty",
		key: "3b",
		require: ["2b"],
		enemy: "",
		background: "background_plains_4",
	},
	{
		x: 1600,
		y: 540,
		title: "Boss",
		key: "4",
		require: ["3a", "3b"],
		enemy: "",
		background: "background_plains_0",
	},
];
